title: Concurrent Message Processing
description: |-
  By default, when a subscription is created, each message that is
  received it process sequentially. There can be multiple subscriptions
  setup in a [queue group][queue] in which case the NATS server will
  distribute messages to each member of the group.

  However, even within a subscription, it may be desirable to handle
  messages concurrently. This example shows how this can be achieved
  in the clients that support it.

  [1]: https://docs.nats.io/nats-concepts/core-nats/queue
