#gobyexample-generated
version: '3.9'
services:
  nats:
    image: docker.io/nats:2.8.4
    command:
      - "--debug"
      - "--http_port=8222"
      - "--js"
    ports:
      - "14222:4222"
      - "18222:8222"

  app:
    build: .
    environment:
      - NATS_URL=nats:4222
    depends_on:
      - nats
