title: JetStream
description: |-
  An [integrated subsystem][jetstream] providing distributed persistence.

  [jetstream]: https://docs.nats.io/nats-concepts/jetstream

examples:
  - limits-stream
  - pull-consumer
  - pull-consumer-limits
  - push-consumer
  - queue-push-consumer
    #  - workqueue-stream
    #  - interests-stream
