title: Private Inbox
description: |-
  Replies to a request using the built-in request-reply pattern
  all share the same subject pattern `_INBOX.>`. For multi-user
  applications where isolation of messages within the same account
  is required, an explicit **inbox prefix** can be used when a
  client connects to the server. This combined with explicit
  permissions prevents users from _snooping_ on service replies.

