title: Intro
description: |
  NATS services have always been straightforward to write. However, with the services
  framework, the NATS client library further simplifies the building, discovery and
  monitoring of services. The framework automatically places all subscriptions in
  a queue group and provides functionality for building subject hierarchies and
  their handlers.

  Without any additional effort, the library enables automatic service discovery
  and status reporting. The NATS CLI `nats micro` command provides a simple way to
  query and report all the services using this framework.
