title: Regional and Cross Region Streams (Cluster)
description: |-
  This example shows and alternative to the [supercluster][1]
  version. Rather than a supercluster, this relies on a nine
  node cluster spread out across three regions and three availability
  zones each.
