title: Mutual TLS
description: |-
  This examples demonstrates a basic embedded server and client
  connection setup utilizing [mTLS](https://en.wikipedia.org/wiki/Mutual_authentication#mTLS).

  This example relies on the [mkcert](https://github.com/FiloSottile/mkcert) tool using
  the commands below to generate the necessary server and client certs. The CA is
  installed in the default location and symlinked for this example.

  ```sh
  mkcert \
    -key-file key.pem \
    -cert-file cert.pem \
    localhost

  mkcert \
    -client \
    -key-file client-key.pem \
    -cert-file client-cert.pem \
    localhost

  ln -s /root/.local/share/mkcert/rootCA.pem ca.pem
  ```
