title: Authentication and Authorization
description: |
  Topics related to [authentication](https://docs.nats.io/running-a-nats-service/configuration/securing_nats/auth_intro) and [authorization](https://docs.nats.io/running-a-nats-service/configuration/securing_nats/authorization).
examples:
  - nkeys-jwts
  - sys-account
  - private-inbox
  - callout
  - callout-decentralized
