title: Messaging
description: |-
  The core messaging capabilities of NATS including
  [pub-sub][1], [request-reply][2], and [queue groups][3].

  [1]: https://docs.nats.io/nats-concepts/core-nats/pubsub
  [2]: https://docs.nats.io/nats-concepts/core-nats/reqreply
  [3]: https://docs.nats.io/nats-concepts/core-nats/queue

examples:
  - pub-sub
  - request-reply
  - json
  - concurrent
  - multiple-subjects-subscription
