title: Topologies
description: |-
  Examples showcasing various deployment topologies NATS supports including
  [clusters][cluster], [superclusters][super], and [leaf nodes][leaf].

  [cluster]: https://docs.nats.io/running-a-nats-service/configuration/clustering
  [super]: https://docs.nats.io/running-a-nats-service/configuration/gateways
  [leaf]: https://docs.nats.io/running-a-nats-service/configuration/leafnodes
examples:
  - simple-leafnode
  - leafnode-jwt
  - supercluster-arbiter
