title: Auth Callout - Centralized
description: |-
  Auth callout is a new feature in NATS v2.10.0 providing an extension point for integrating
  with alternative identity and access management (IAM) backends. See the [official docs][docs]
  for more details.

  This example demonstrates how auth callout can be configured within server configuration.
  This is combined with a basic service that handles the authorization requests delegated
  by the NATS server.

  [docs]: https://docs.nats.io/running-a-nats-service/configuration/security_nats/auth_callout
