name: preview
on: pull_request

jobs:
  run:
    name: Preview
    runs-on: "ubuntu-latest"

    permissions:
      contents: write
      issues: write
      pull-requests: write
      statuses: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install Asciinema
        run: |
          python3 -m pip install asciinema

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.21"
          cache-dependency-path: cmd/nbe/go.sum

      - name: Test nbe
        run: |
          go test -v -race ./cmd/nbe

      - name: Build nbe
        run: |
          go install ./cmd/nbe

      - name: Generate recordings
        shell: 'script -q -e -c "bash {0}"'
        run: |
          nbe generate recording --exit-on-error

      - name: Build HTML
        run: |
          nbe build

      - name: Vercel preview deploy
        uses: amondnet/vercel-action@v25
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          scope: ${{ secrets.VERCEL_TEAM_SCOPE }}
          working-directory: ./html
